name: staging

on:
  push:
    branches: [ dev ]
    #Disable action for unrelated build stuff
    paths-ignore:
      - 'CHANGELOG.md'
      - 'version.txt'
      - '.github/workflows/prod.yml'
      - 'README.md'
      - 'doc/*'
  pull_request:
    branches: [ dev ]
    #Disable action for unrelated build stuff
    paths-ignore:
      - 'CHANGELOG.md'
      - 'version.txt'
      - '.github/workflows/prod.yml'
      - 'README.md'
      - 'doc/*'

  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    environment: staging

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: xdebug
      - uses: actions/checkout@v4

      #SETUP LARAVEL
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
         mkdir -p database
         touch database/database.sqlite

      - name: Setup node for dist build
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm'

      - name: generate dist
        run: |
          npm install
          npm run build:vite

      #TESTS
      - name: Execute tests (Unit and Feature tests) via Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: "database/database.sqlite"
        run: php artisan test -p --coverage-clover clover.xml

      #Generates a new cache on updated manifest and validated tests
      - uses: actions/cache@v4
        with:
         path: public/build
         key: vite-assets-${{ hashFiles('public/build/manifest.json') }}

      - name: Generate coverage badge
        # You may pin to the exact commit or the version.
        # uses: timkrase/phpunit-coverage-badge@29e63a46fd2b558fadefaa1699c6aa5892bd5791
        uses: timkrase/phpunit-coverage-badge@v1.2.0
        with:
          # The path to the report file generated by PHPUnit.
          report: clover.xml # optional, default is clover.xml

      - name: Push badge/wip-version to FTP
        # You may pin to the exact commit or the version.
        # uses: sand4rt/ftp-deployer@d10dbc869c419015125bc9bfa5e1267056fb822d
        uses: sand4rt/ftp-deployer@v1.8
        with:
          # FTP host URL like: ftp.host.com or sftp.host.com
          host: ${{ secrets.BADGE_FTP_HOST }}
          # Ftp username
          username: ${{ secrets.BADGE_FTP_USER }}
          # Ftp password
          password: ${{ secrets.BADGE_FTP_PASS }}
          local_folder: './'
          # includes
          include: '["coverage_badge.svg"]'

  deploy-to-staging:
    needs: test
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: staging
