name: staging

on:
  push:
    branches: [ main ]
    #Disable action for unrelated build stuff
    paths-ignore:
      - 'CHANGELOG.md'
      - 'version.txt'
      - '.github/workflows/prod.yml'
      - 'README.md'
      - 'doc/*'
  pull_request:
    branches: [ main ]
    #Disable action for unrelated build stuff
    paths-ignore:
      - 'CHANGELOG.md'
      - 'version.txt'
      - '.github/workflows/prod.yml'
      - 'README.md'
      - 'doc/*'

  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    environment: staging

    steps:
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          coverage: xdebug
      - uses: actions/checkout@v3

      #SETUP LARAVEL
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Create Database
        run: |
          mkdir -p database
          touch database/database.sqlite
      #TESTS
      - name: Execute tests (Unit and Feature tests) via Pest
        env:
          DB_CONNECTION: sqlite
          DB_DATABASE: database/database.sqlite
        run: php artisan test --coverage-clover clover.xml

      - name: Generate coverage badge
        # You may pin to the exact commit or the version.
        # uses: timkrase/phpunit-coverage-badge@29e63a46fd2b558fadefaa1699c6aa5892bd5791
        uses: timkrase/phpunit-coverage-badge@v1.2.0
        with:
          # The path to the report file generated by PHPUnit.
          report: clover.xml # optional, default is clover.xml

      - name: Update version for staging
        run: |
          latestTag=$(basename $(curl -fs -o/dev/null -w %{redirect_url} ${{github.server_url}}/${{github.repository}}/releases/latest))
          latestSha=$(curl ${{github.api_url}}/repos/${{github.repository}}/git/ref/tags/$latestTag 2>/dev/null | grep sha | awk -F'"' '{ print $4 }')
          if [ "$latestSha" = "${{ github.sha }}" ] ; then
            echo "Release deploy detected, set wip version to $latestTag"
            cp version.txt version-wip.txt
          else
            shortSha=$(echo ${{ github.sha }} | cut -c1-8)
            echo "WIP deploy detected, set wip version to $shortSha"
            echo "$shortSha" > version-wip.txt
          fi

      - name: Push badge/wip-version to FTP
        # You may pin to the exact commit or the version.
        # uses: sand4rt/ftp-deployer@d10dbc869c419015125bc9bfa5e1267056fb822d
        uses: sand4rt/ftp-deployer@v1.4
        with:
          # FTP host URL like: ftp.host.com or sftp.host.com
          host: ${{ secrets.BADGE_FTP_HOST }}
          # Ftp username
          username: ${{ secrets.BADGE_FTP_USER }}
          # Ftp password
          password: ${{ secrets.BADGE_FTP_PASS }}
          local_folder: './'
          # includes
          include: '["coverage_badge.svg","version-wip.txt"]'

  deploy-to-staging:
    needs: test
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: staging
